FROM node:19.2-alpine
WORKDIR /app
COPY package.json .
COPY public/ /app/public/
RUN npm install
COPY . /app/
RUN yarn build
EXPOSE 80
RUN yarn global add serve
CMD [ "serve", "-s", "build", "-l", "80" ]