FROM node:19.2-alpine as build
WORKDIR /app
COPY package.json .
COPY public/ /app/public/
RUN npm install
COPY . /app/
RUN yarn build

FROM nginx:stable-alpine as serve
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]