name: Release
on:
  push:
    branches:
      - ma/env_var

jobs:
  publish_latest_on_dockerhub:
    name: Publish on dockerhub as latest
    runs-on: ubuntu-latest
    environment: qlf

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: maximallain/cosia_front:env_var_qlf
          file: Dockerfile.qlf

  # Unabled because of IGN network... When l'usine logicielle is open on internet => let's go !
  # trigger_deployment_pipeline:
  #   name: Trigger deployment pipeline
  #   runs-on: ubuntu-latest
  #   needs:
  #     - publish_latest_on_dockerhub
  #   steps:
  #     - name: Fetch gitlab webhook
  #       uses: joelwmale/webhook-action@master
  #       with:
  #         url: https://gitlab.gpf-tech.ign.fr/api/v4/projects/701/ref/master/trigger/pipeline?token=${{ secrets.DEV_TRIGGER_GITLAB_TOKEN }}

  publish_version_on_dockerhub:
    name: Publish new tag on dockerhub
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: maximallain/cosia_front:env_var_prd
          file: Dockerfile.prod
